name: AutoRegister
on:
  workflow_run:
    workflows: ['Release Drafter']
    types: [completed]
    branches: [main]
jobs:
  autoregister:
    permissions:
      contents: write
      issues: write
    uses: lab-sotashimozono/.github/.github/workflows/autoregister.yml@main
    secrets: inherit
